# Generated by Django 6.0.1 on 2026-01-25 04:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('scraper', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='section',
            name='heading',
            field=models.TextField(blank=True),
        ),
    ]
